---
- name: BMC sushy-tools Setup | Deploy sushy-tools emulator
  hosts: vm_host
  roles:
    - role: ansible-sushy-tools-podman
      sushy_host: "{{ ztp_bmc_host | default(omit, true) }}"
      sushy_port: "{{ ztp_bmc_port | default(omit, true) }}"
      sushy_admin_user: "{{ ztp_bmc_username | default(omit, true) }}"
      sushy_admin_password: "{{ ztp_bmc_password | default(omit, true) }}"