apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  provisioningNetwork: Disabled
  provisioningMacAddresses:
    - empty
  watchAllNamespaces: true
  virtualMediaViaExternalNetwork: true
