apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  preProvisioningOSDownloadURLs: {}
  provisioningNetwork: Disabled
  provisioningOSDownloadURL: ""
  virtualMediaViaExternalNetwork: true
  watchAllNamespaces: true
