---
collections:
  - ansible.posix
  - ansible.utils
  - community.crypto
  - community.general
  - containers.podman

roles:
  - name: ansible-sushy-tools-podman
    src: https://github.com/kubealex/ansible-sushy-tools-podman.git
